// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makeCueSplitsC
NumericMatrix makeCueSplitsC(NumericVector criterion, NumericVector cue);
RcppExport SEXP _ffcr_makeCueSplitsC(SEXP criterionSEXP, SEXP cueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cue(cueSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCueSplitsC(criterion, cue));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ffcr_makeCueSplitsC", (DL_FUNC) &_ffcr_makeCueSplitsC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ffcr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
